import { Router } from "express";
import { PageContent } from "../lib/db-mongoose/index.js";

interface PageSection { key: string; label: string; type: "text" | "textarea"; value: string; }
interface DefaultPageDef { name: string; isSystem: boolean; frontendUrl: string; sections: PageSection[]; }

const t = (k: string, l: string, v: string): PageSection => ({ key: k, label: l, type: "text", value: v });
const ta = (k: string, l: string, v: string): PageSection => ({ key: k, label: l, type: "textarea", value: v });

const DEFAULT_PAGES: Record<string, DefaultPageDef> = {
  "home": {
    name: "Home",
    isSystem: true,
    frontendUrl: "/",
    sections: [
      ta("hero_description", "Hero – Description", "Buy tokens, join lucky draws, and win big — 100% transparent system with verified winners."),
      t("trust1_title", "Trust Badge 1 – Title", "Verified Winners"),
      t("trust1_sub", "Trust Badge 1 – Subtitle", "Real people, Real wins"),
      t("trust2_title", "Trust Badge 2 – Title", "Transparent System"),
      t("trust2_sub", "Trust Badge 2 – Subtitle", "Fair & Random Draws"),
      t("trust3_title", "Trust Badge 3 – Title", "Secure Payments"),
      t("trust3_sub", "Trust Badge 3 – Subtitle", "Your safety is our priority"),
      t("draws_title", "Draws Section – Title", "Live Draws Right Now"),
      ta("draws_subtitle", "Draws Section – Subtitle", "Purchase tokens for the specific prize you want. Draws happen live when the token limit is reached."),
      t("hiw_title", "How It Works – Title", "Transparent & Simple"),
      ta("hiw_subtitle", "How It Works – Subtitle", "We operate on complete transparency. Every draw is verifiable, and winners are announced publicly."),
      t("hiw_step1_title", "How It Works – Step 1 Title", "Buy a Token"),
      ta("hiw_step1_desc", "How It Works – Step 1 Description", "Select the prize you want to win and purchase a token starting from just Rs. 100. Payments are secure."),
      t("hiw_step2_title", "How It Works – Step 2 Title", "Wait for the Target"),
      ta("hiw_step2_desc", "How It Works – Step 2 Description", "Each draw has a fixed number of tokens. The draw triggers automatically once all tokens are sold."),
      t("hiw_step3_title", "How It Works – Step 3 Title", "Live Draw & Win"),
      ta("hiw_step3_desc", "How It Works – Step 3 Description", "Watch the draw live. Our provably fair system selects a winner randomly. Instant payout/delivery."),
      t("faq_title", "FAQ Section – Title", "Frequently Asked Questions"),
      ta("faq_subtitle", "FAQ Section – Subtitle", "Everything you need to know before joining your first draw."),
      t("faq1_q", "FAQ 1 – Question", "How do I know the draws are fair?"),
      ta("faq1_a", "FAQ 1 – Answer", "We use a provably fair cryptographic system. The outcome is generated by combining a server seed (which is hidden until the draw) and a public client seed (e.g., the closing hash of a Bitcoin block). This makes it mathematically impossible for us or anyone else to manipulate the result."),
      t("faq2_q", "FAQ 2 – Question", "How are physical prizes delivered?"),
      ta("faq2_a", "FAQ 2 – Answer", "For cars and bikes, we arrange a secure handover ceremony at our regional offices in Karachi, Lahore, or Islamabad. If you live outside these cities, we handle secure transportation directly to you."),
      t("faq3_q", "FAQ 3 – Question", "What happens if a draw doesn't sell out?"),
      ta("faq3_a", "FAQ 3 – Answer", "Draws only trigger when 100% of the tokens are sold. If a draw doesn't sell out within 90 days, all participants receive a full refund to their wallet."),
      t("faq4_q", "FAQ 4 – Question", "Can I participate from outside Pakistan?"),
      ta("faq4_a", "FAQ 4 – Answer", "Currently, Kaptan Lucky Draw is only available to residents of Pakistan. You must have a valid CNIC to claim physical prizes or withdraw cash to a local bank account."),
      t("cta_title", "CTA – Title", "Ready to Try Your Luck?"),
      ta("cta_subtitle", "CTA – Subtitle", "Join thousands of users already participating in our lucky draws."),
    ],
  },

  "about": {
    name: "About Us",
    isSystem: true,
    frontendUrl: "/about",
    sections: [
      ta("hero_subtitle", "Hero – Subtitle", "Creating a transparent and exciting way for people to win amazing prizes."),
      ta("hero_body", "Hero – Body", "Kaptan Lucky Draw is a modern digital lucky draw platform designed to give everyone a fair chance to win big prizes. With our secure token system and transparent draw process, users can participate confidently and enjoy the thrill of winning."),
      ta("mission_title", "Mission – Title", "Fair chances for everyone, big or small."),
      ta("mission_body", "Mission – Body", "Our mission is to create a fair, transparent, and exciting platform where anyone can participate in lucky draws and win valuable prizes without needing a large investment. We believe everyone deserves a chance to win big."),
      ta("vision_title", "Vision – Title", "The most trusted draw platform in Pakistan."),
      ta("vision_body", "Vision – Body", "Our vision is to become one of the most trusted digital lucky draw platforms by building a transparent system that users can rely on. We aim to create a community where fairness, excitement, and trust come together."),
      ta("whatis_body", "What Is – Body", "Kaptan Lucky Draw is an online platform where users purchase tokens to participate in lucky draws for exciting prizes such as cars, bikes, and cash rewards. Each token gives the user a chance to win, and winners are selected using a fair and transparent draw system."),
      ta("transparency_body", "Transparency – Body", "Trust is the foundation of our platform. Every step of every draw is designed to be visible, verifiable, and impartial — so you can participate with complete confidence."),
      t("transparency_p1", "Transparency – Point 1", "Every token has equal winning chance"),
      t("transparency_p2", "Transparency – Point 2", "Draws are conducted live and fairly"),
      t("transparency_p3", "Transparency – Point 3", "All winners are announced publicly"),
      t("transparency_p4", "Transparency – Point 4", "Results are recorded and verifiable"),
      t("trust_subtitle", "Why Trust – Subtitle", "Four pillars that hold up everything we do."),
      t("trust1_title", "Why Trust – Card 1 Title", "Transparent Draw System"),
      ta("trust1_desc", "Why Trust – Card 1 Description", "Every draw uses a provably-fair algorithm with public results."),
      t("trust2_title", "Why Trust – Card 2 Title", "Verified Winners"),
      ta("trust2_desc", "Why Trust – Card 2 Description", "All winners publicly announced with masked names and token IDs."),
      t("trust3_title", "Why Trust – Card 3 Title", "Secure Payment Methods"),
      ta("trust3_desc", "Why Trust – Card 3 Description", "Trusted payment partners — Easypaisa, JazzCash, Sadapay, banks."),
      t("trust4_title", "Why Trust – Card 4 Title", "Active Support Team"),
      ta("trust4_desc", "Why Trust – Card 4 Description", "Real human support on WhatsApp every day, 10 AM – 10 PM."),
      t("stat1_value", "Stats – Stat 1 Value", "50,000+"),
      t("stat1_label", "Stats – Stat 1 Label", "Active Users"),
      t("stat2_value", "Stats – Stat 2 Value", "1M+"),
      t("stat2_label", "Stats – Stat 2 Label", "Tokens Sold"),
      t("stat3_value", "Stats – Stat 3 Value", "1,200+"),
      t("stat3_label", "Stats – Stat 3 Label", "Prizes Won"),
      t("stat4_value", "Stats – Stat 4 Value", "100%"),
      t("stat4_label", "Stats – Stat 4 Label", "Transparent Draws"),
      t("community_title", "Community – Title", "A Community Built on Trust & Excitement"),
      ta("community_body", "Community – Body", "Our platform continues to grow as more users join our community every day. We are committed to improving our platform, adding new prize categories, and providing exciting opportunities for everyone."),
      t("cta_title", "CTA – Title", "Ready to Try Your Luck?"),
      ta("cta_subtitle", "CTA – Subtitle", "Join thousands of users already participating in our lucky draws."),
    ],
  },

  "how-it-works": {
    name: "How It Works",
    isSystem: true,
    frontendUrl: "/how-it-works",
    sections: [
      ta("hero_subtitle", "Hero – Subtitle", "Kaptan Lucky Draw makes winning exciting prizes simple. Follow the steps below to buy tokens, join draws, and win amazing prizes."),
      t("timeline_title", "Timeline – Title", "Four Steps to Winning"),
      ta("timeline_subtitle", "Timeline – Subtitle", "From your first token to your prize handover — here's everything that happens."),
      t("step1_title", "Step 1 – Title", "Buy Tokens"),
      ta("step1_desc", "Step 1 – Description", "Choose your favorite draw and purchase tokens to participate. Each token gives you an entry into the lucky draw."),
      ta("step1_detail", "Step 1 – Detail", "Tokens are affordable and buying multiple tokens increases your winning chances."),
      t("step2_title", "Step 2 – Title", "Submit Payment"),
      ta("step2_desc", "Step 2 – Description", "Complete your payment using supported methods and upload your payment proof for verification."),
      ta("step2_detail", "Step 2 – Detail", "Payments are verified by the admin team and tokens are added once approved."),
      t("step3_title", "Step 3 – Title", "Receive Your Entries"),
      ta("step3_desc", "Step 3 – Description", "Once your payment is verified, your tokens are converted into entries with a unique ID for the selected draw."),
      ta("step3_detail", "Step 3 – Detail", "Every entry receives an equal chance of winning — no preferences, no insiders."),
      t("step4_title", "Step 4 – Title", "Win the Prize"),
      ta("step4_desc", "Step 4 – Description", "When the draw closes, our secure system randomly selects a winning entry. Winners are announced publicly."),
      ta("step4_detail", "Step 4 – Detail", "Prizes are delivered fast — cash within hours, physical prizes within days."),
      ta("token_subtitle", "Token – Subtitle", "A token is your entry into a lucky draw. Each token represents one chance to win — the more tokens you hold, the higher your odds."),
      t("payment_title", "Payment – Title", "Pay & Get Verified Fast"),
      ta("payment_subtitle", "Payment – Subtitle", "From submitting payment to receiving entries — usually under an hour."),
      t("draw_title", "Draw System – Title", "How Winners Are Picked"),
      ta("draw_subtitle", "Draw System – Subtitle", "Every entry has an exactly equal probability — no exceptions, no preferences."),
      t("faq1_q", "FAQ 1 – Question", "Is Kaptan Lucky Draw real?"),
      ta("faq1_a", "FAQ 1 – Answer", "Yes — we are a registered Pakistani entity with a public office, verified winners, and recorded draws. Every payout is documented and visible on our winners page."),
      t("faq2_q", "FAQ 2 – Question", "How are winners selected?"),
      ta("faq2_a", "FAQ 2 – Answer", "Winners are selected by a provably-fair random algorithm that uses a hidden server seed combined with a public client seed. The result cannot be predicted or manipulated by anyone."),
      t("faq3_q", "FAQ 3 – Question", "How many tokens can I buy?"),
      ta("faq3_a", "FAQ 3 – Answer", "There is no per-user limit on tokens. You can buy as many tokens as you want for any active draw, up to the total token supply for that draw."),
      t("faq4_q", "FAQ 4 – Question", "Can I join multiple draws?"),
      ta("faq4_a", "FAQ 4 – Answer", "Absolutely. You can hold tokens across as many active draws as you like. Each draw is independent and your odds in each are calculated separately."),
      t("faq5_q", "FAQ 5 – Question", "How will I receive my prize?"),
      ta("faq5_a", "FAQ 5 – Answer", "Cash prizes are sent to your wallet (Easypaisa, JazzCash, SadaPay or bank) within hours of the draw. Physical prizes are handed over in our regional offices or delivered to your address securely."),
      t("faq6_q", "FAQ 6 – Question", "What happens if a draw does not fill?"),
      ta("faq6_a", "FAQ 6 – Answer", "If a draw does not reach 100% sold within 90 days, all participants are refunded the full token amount to their wallet — no fees, no questions."),
      t("cta_title", "CTA – Title", "Ready to Try Your Luck?"),
      ta("cta_subtitle", "CTA – Subtitle", "Join thousands of participants already winning exciting prizes on Kaptan Lucky Draw."),
    ],
  },

  "contact": {
    name: "Contact Us",
    isSystem: true,
    frontendUrl: "/contact",
    sections: [
      t("support_email", "Contact – Support Email", "support@captainluckydraw.com"),
      t("support_hours", "Contact – Support Hours", "10 AM – 10 PM"),
      ta("hero_subtitle", "Hero – Subtitle", "Our support team is ready to assist you with payments, tokens, draws, and account questions."),
    ],
  },

  "refer-earn": {
    name: "Refer & Earn",
    isSystem: true,
    frontendUrl: "/refer",
    sections: [
      ta("hero_subtitle", "Hero – Subtitle", "Users who buy 100 or more tokens unlock a referral link in their account. When someone signs up through that link, only the referrer gets 1 free draw token."),
      t("hiw_title", "How It Works – Title", "How It Works"),
      ta("hiw_subtitle", "How It Works – Subtitle", "Only eligible accounts can create a referral link after purchasing 100 or more tokens."),
      t("step1_title", "Step 1 – Title", "Share Your Referral"),
      ta("step1_desc", "Step 1 – Description", "Log in to your dashboard after buying 100 or more tokens to see your unique referral link."),
      t("step2_title", "Step 2 – Title", "Friend Signs Up"),
      ta("step2_desc", "Step 2 – Description", "A new user creates an account using your referral link. The referral reward is credited only to the eligible referrer."),
      t("step3_title", "Step 3 – Title", "1 Token for Referrer"),
      ta("step3_desc", "Step 3 – Description", "When the referral is completed, only the account owner who shared the link receives 1 free draw token."),
      t("rewards_title", "Rewards – Title", "What You Earn"),
      ta("rewards_subtitle", "Rewards – Subtitle", "Referral access is unlocked only for users who purchase 100 or more tokens."),
      t("cta_title", "CTA – Title", "Ready to Start Earning?"),
      ta("cta_subtitle", "CTA – Subtitle", "After buying 100 or more tokens, your dashboard will show your referral link."),
    ],
  },

  "winners": {
    name: "Winners",
    isSystem: true,
    frontendUrl: "/winners",
    sections: [],
  },
};

function mergeWithDefaults(slug: string, dbSections: PageSection[]): PageSection[] {
  const def = DEFAULT_PAGES[slug];
  if (!def) return dbSections;
  const merged = def.sections.map(defSec => {
    const saved = dbSections.find(s => s.key === defSec.key);
    return saved ? { ...defSec, value: saved.value } : defSec;
  });
  const defaultKeys = new Set(def.sections.map(s => s.key));
  const extras = dbSections.filter(s => !defaultKeys.has(s.key));
  return [...merged, ...extras];
}

const router = Router();

router.get("/pages/:slug", async (req, res) => {
  try {
    const { slug } = req.params;
    const dbPage = await PageContent.findOne({ slug });
    if (dbPage) {
      const sections = mergeWithDefaults(slug, (dbPage.sections as PageSection[]) || []);
      return res.json({ ...dbPage.toObject(), sections });
    }
    const def = DEFAULT_PAGES[slug];
    if (def) {
      return res.json({
        id: null,
        slug,
        name: def.name,
        isSystem: true,
        published: true,
        sections: def.sections,
      });
    }
    return res.status(404).json({ error: "Page not found" });
  } catch {
    res.status(500).json({ error: "Server error" });
    return;
  }
});

export default router;
